### ISSUE TITLE
12.10失效

### ISSUE THREAD

**Issue by 1154450477** [ZimoLoveShuang/auto-submit#27]
Traceback (most recent call last):
  File "/opt/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/var/lang/python3/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/opt/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/opt/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/opt/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/opt/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: &lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f80e71f2748&gt;: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.cpdaily.com', port=443): Max retries exceeded with url: /v6/config/guest/tenant/list (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f80e71f2748&gt;: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/runtime/python3/bootstrap.py", line 176, in handle
    ret = self.real_handler(event, context)
  File "/var/user/index.py", line 380, in main_handler
    raise e
  File "/var/user/index.py", line 343, in main_handler
    apis = getCpdailyApis(user)
  File "/var/user/index.py", line 38, in getCpdailyApis
    url='https://www.cpdaily.com/v6/config/guest/tenant/list', verify=not debug).json()['data']
  File "/opt/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/opt/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.cpdaily.com', port=443): Max retries exceeded with url: /v6/config/guest/tenant/list (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f80e71f2748&gt;: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by nicolas772580** [comment]
俺也一样

**Comment by yaonyan** [comment]
`www.cpdaily.com` 域名弃用 ，API 更改，见 [PR](https://github.com/ZimoLoveShuang/auto-sign/pull/29/files)

**Comment by 1154450477** [comment]
> `www.cpdaily.com` 域名弃用 ，API 更改，见 [PR](https://github.com/ZimoLoveShuang/auto-sign/pull/29/files)

谢谢
