### ISSUE TITLE
求援求援

### ISSUE THREAD

**Issue by AxisRR** [ZimoLoveShuang/auto-submit#43]
Traceback (most recent call last):
  File "index.py", line 82, in <module>
    main()
  File "index.py", line 23, in main
    msg = working(user)
  File "index.py", line 51, in working
    sign.fillForm()
  File "/home/ahcheer/auto-submit-ruoli/今日校园/actions/autoSign.py", line 129, in fillForm
    self.form['abnormalReason'] = self.userInfo['abnormalReason']
KeyError: 'abnormalReason'

**Comment by nier9x** [comment]
我也是这个问题

**Comment by lthero-big** [comment]
#abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
abnormalReason: ''
在config.yml的每个user里面添加这句话
