### ISSUE TITLE
python运行报错，求指教

### ISSUE THREAD

**Issue by mhlms** [ZimoLoveShuang/auto-submit#48]
Traceback (most recent call last):
  File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 365, in main_handler
    InfoSubmit('自动提交成功！', user['user']['email'])
  File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 336, in InfoSubmit
    if(config['Info']['ServerChan']): sendServerChan(msg)
  File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 312, in sendServerChan
    code = res.json()['errmsg']
KeyError: 'errmsg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 388, in <module>
    print(main_handler({}, {}))
  File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 380, in main_handler
    InfoSubmit("出现问题了！"+str(e))
  File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 336, in InfoSubmit
    if(config['Info']['ServerChan']): sendServerChan(msg)
  File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 312, in sendServerChan
    code = res.json()['errmsg']
KeyError: 'errmsg'

**Comment by mhlms** [comment]
成功提交，但是出现这样的错误，不知道是不是哪里没有配置好。

**Comment by mhlms** [comment]
> Traceback (most recent call last):
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 365, in main_handler
> InfoSubmit('自动提交成功！', user['user']['email'])
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 336, in InfoSubmit
> if(config['Info']['ServerChan']): sendServerChan(msg)
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 312, in sendServerChan
> code = res.json()['errmsg']
> KeyError: 'errmsg'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 388, in
> print(main_handler({}, {}))
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 380, in main_handler
> InfoSubmit("出现问题了！"+str(e))
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 336, in InfoSubmit
> if(config['Info']['ServerChan']): sendServerChan(msg)
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 312, in sendServerChan
> code = res.json()['errmsg']
> KeyError: 'errmsg'

**Comment by mhlms** [comment]
> Traceback (most recent call last):
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 365, in main_handler
> InfoSubmit('自动提交成功！', user['user']['email'])
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 336, in InfoSubmit
> if(config['Info']['ServerChan']): sendServerChan(msg)
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 312, in sendServerChan
> code = res.json()['errmsg']
> KeyError: 'errmsg'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 388, in
> print(main_handler({}, {}))
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 380, in main_handler
> InfoSubmit("出现问题了！"+str(e))
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 336, in InfoSubmit
> if(config['Info']['ServerChan']): sendServerChan(msg)
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 312, in sendServerChan
> code = res.json()['errmsg']
> KeyError: 'errmsg'

**Comment by mhlms** [comment]
> Traceback (most recent call last):
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 365, in main_handler
> InfoSubmit('自动提交成功！', user['user']['email'])
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 336, in InfoSubmit
> if(config['Info']['ServerChan']): sendServerChan(msg)
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 312, in sendServerChan
> code = res.json()['errmsg']
> KeyError: 'errmsg'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 388, in
> print(main_handler({}, {}))
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 380, in main_handler
> InfoSubmit("出现问题了！"+str(e))
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 336, in InfoSubmit
> if(config['Info']['ServerChan']): sendServerChan(msg)
> File "D:\PythonCode\pythonProject\auto-submit-master\index.py", line 312, in sendServerChan
> code = res.json()['errmsg']
> KeyError: 'errmsg'
