### ISSUE TITLE
我添加了hosts，依然运行报错。

### ISSUE THREAD

**Issue by YangNaner** [ZimoLoveShuang/auto-submit#51]
2022-01-06 17:16:52 当前用户：161105024
Traceback (most recent call last):
  File "C:\Users\小明\Desktop\auto-submit-master\index.py", line 388, in <module>
    print(main_handler({}, {}))
  File "C:\Users\小明\Desktop\auto-submit-master\index.py", line 381, in main_handler
    raise e
  File "C:\Users\小明\Desktop\auto-submit-master\index.py", line 344, in main_handler
    apis = getCpdailyApis(user)
  File "C:\Users\小明\Desktop\auto-submit-master\index.py", line 37, in getCpdailyApis
    schools = requests.get(
  File "D:\Program Files\Python39\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Program Files\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by wyek1n** [comment]
同报错，蹲个大佬。

Traceback (most recent call last):
  File "/root/auto-submit/currency/login.py", line 75, in <module>
    apis = getCpdailyApis(user)
  File "/root/auto-submit/currency/login.py", line 29, in getCpdailyApis
    schools = requests.get(url='https://www.cpdaily.com/v6/config/guest/tenant/list', verify=not debug).json()['data']
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
